### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by legalsylvain** [grap/grap-odoo-custom#374]
- [x] fermente_stock - By @legalsylvain - #375
- [x] fermente_web_environment_ribbon - By @legalsylvain - #372
- [x] mrp_bom_wizard_production - By @quentinDupont - #371
- [x] server_environment_files - By @legalsylvain - #373
